import { Word, Difficulty, Topic } from './types';

const w = (id: string, e: string, a: string, ex: string, s: string[], d: Difficulty, t: Topic): Word => ({ id, english: e, arabic: a, example: ex, synonyms: s, difficulty: d, topic: t });

export const INITIAL_WORDS: Word[] = [
  // --- TASK 1: TRENDS & ACADEMIC ---
  w('101', 'increase', 'يزداد / يرتفع', 'The number of students increased significantly.', ['rise', 'grow', 'climb'], Difficulty.Basic, Topic.Academic),
  w('102', 'decrease', 'ينخفض / يقل', 'Unemployment rates decreased slightly.', ['fall', 'drop', 'decline'], Difficulty.Basic, Topic.Academic),
  w('103', 'fluctuate', 'يتذبذب', 'Gold prices tend to fluctuate wildly.', ['oscillate', 'vary', 'waver'], Difficulty.Intermediate, Topic.Academic),
  w('104', 'stabilize', 'يستقر', 'After a period of volatility, the figures stabilized.', ['level off', 'plateau', 'steady'], Difficulty.Intermediate, Topic.Academic),
  w('105', 'plummet', 'يهبط بشدة', 'Profits plummeted after the scandal.', ['plunge', 'crash', 'collapse'], Difficulty.Advanced, Topic.Academic),
  w('106', 'soar', 'يرتفع بسرعة هائلة', 'Demand for electric cars soared.', ['rocket', 'surge', 'skyrocket'], Difficulty.Advanced, Topic.Academic),
  w('107', 'gradual', 'تدريجي', 'There was a gradual increase in temperature.', ['steady', 'slow', 'progressive'], Difficulty.Intermediate, Topic.Academic),
  w('108', 'dramatic', 'درامي / ملحوظ جدا', 'A dramatic shift in behavior was observed.', ['sharp', 'substantial', 'significant'], Difficulty.Intermediate, Topic.Academic),
  w('109', 'respectively', 'على التوالي', 'Japan and Korea won 10 and 8 medals, respectively.', ['in that order', 'correspondingly'], Difficulty.Intermediate, Topic.Academic),
  w('110', 'account for', 'يمثل / يشكل نسبة', 'Oil exports account for 80% of revenue.', ['comprise', 'constitute', 'make up'], Difficulty.Intermediate, Topic.Academic),
  w('111', 'peak', 'يصل للقمة', 'Sales peaked in December.', ['reach a high', 'climax', 'top out'], Difficulty.Basic, Topic.Academic),
  w('112', 'witness', 'يشهد', 'The period witnessed a sharp turnaround.', ['experience', 'observe', 'see'], Difficulty.Intermediate, Topic.Academic),
  w('113', 'marginal', 'هامشي / بسيط', 'There was only a marginal difference.', ['slight', 'insignificant', 'negligible'], Difficulty.Advanced, Topic.Academic),
  w('114', 'considerable', 'معتبر / كبير', 'A considerable amount of money was spent.', ['significant', 'substantial', 'sizable'], Difficulty.Intermediate, Topic.Academic),
  w('115', 'consistent', 'ثابت / متسق', 'The figures remained consistent throughout the year.', ['constant', 'steady', 'stable'], Difficulty.Intermediate, Topic.Academic),
  w('116', 'trajectory', 'مسار', 'The graph shows the upward trajectory of sales.', ['path', 'course', 'track'], Difficulty.Advanced, Topic.Academic),
  w('117', 'projection', 'توقع / تقدير', 'Current projections show a decline next year.', ['prediction', 'forecast', 'estimate'], Difficulty.Advanced, Topic.Academic),
  w('118', 'surpass', 'يتجاوز / يتفوق', 'Exports surpassed imports in 2022.', ['exceed', 'outperform', 'beat'], Difficulty.Intermediate, Topic.Academic),
  w('119', 'overtake', 'يتجاوز', 'China overtook the US as the top manufacturer.', ['pass', 'go past', 'outstrip'], Difficulty.Intermediate, Topic.Academic),
  w('120', 'plateau', 'يستقر (بعد صعود)', 'Sales rose then plateaued in Q3.', ['level off', 'flatten out'], Difficulty.Advanced, Topic.Academic),
  w('121', 'correlation', 'ارتباط', 'There is a correlation between education and income.', ['connection', 'link', 'relationship'], Difficulty.Advanced, Topic.Academic),
  w('122', 'inverse', 'عكسي', 'There is an inverse relationship between supply and price.', ['opposite', 'reverse', 'contrary'], Difficulty.Advanced, Topic.Academic),
  w('123', 'proportion', 'نسبة / حصة', 'A large proportion of the budget goes to health.', ['percentage', 'share', 'fraction'], Difficulty.Basic, Topic.Academic),
  w('124', 'illustrate', 'يوضح', 'The chart illustrates the breakdown of energy use.', ['show', 'demonstrate', 'depict'], Difficulty.Intermediate, Topic.Academic),
  w('125', 'comparison', 'مقارنة', 'In comparison to 2010, 2020 saw less rain.', ['contrast', 'juxtaposition'], Difficulty.Basic, Topic.Academic),
  w('126', 'trend', 'اتجاه', 'The overall trend is upward.', ['pattern', 'movement', 'tendency'], Difficulty.Basic, Topic.Academic),
  w('127', 'rapid', 'سريع', 'There was a rapid growth in users.', ['fast', 'swift', 'quick'], Difficulty.Basic, Topic.Academic),
  w('128', 'steep', 'حاد / شديد الانحدار', 'A steep fall in prices occurred.', ['sharp', 'abrupt', 'precipitous'], Difficulty.Intermediate, Topic.Academic),
  w('129', 'dip', 'انخفاض بسيط', 'There was a slight dip in August.', ['drop', 'decline', 'fall'], Difficulty.Basic, Topic.Academic),
  w('130', 'erratic', 'غير منتظم', 'The numbers were erratic throughout the period.', ['unpredictable', 'irregular', 'inconsistent'], Difficulty.Advanced, Topic.Academic),

  // --- ENVIRONMENT ---
  w('201', 'detrimental', 'ضار', 'Smoking is detrimental to health.', ['harmful', 'damaging', 'injurious'], Difficulty.Advanced, Topic.Environment),
  w('202', 'mitigate', 'يخفف', 'We must mitigate the effects of pollution.', ['alleviate', 'reduce', 'diminish'], Difficulty.Advanced, Topic.Environment),
  w('203', 'sustainable', 'مستدام', 'We need sustainable energy sources.', ['renewable', 'eco-friendly', 'viable'], Difficulty.Intermediate, Topic.Environment),
  w('204', 'biodiversity', 'تنوع بيولوجي', 'Loss of biodiversity threatens the ecosystem.', ['ecological variety', 'variety of life'], Difficulty.Advanced, Topic.Environment),
  w('205', 'contamination', 'تلوث', 'Water contamination is a major issue.', ['pollution', 'impurity', 'poisoning'], Difficulty.Intermediate, Topic.Environment),
  w('206', 'conservation', 'حماية / حفظ', 'Wildlife conservation is essential.', ['preservation', 'protection', 'safeguarding'], Difficulty.Intermediate, Topic.Environment),
  w('207', 'deplete', 'يستنزف', 'Humans are depleting natural resources.', ['exhaust', 'use up', 'drain'], Difficulty.Advanced, Topic.Environment),
  w('208', 'habitat', 'موطن طبيعي', 'Deforestation destroys animal habitats.', ['environment', 'home', 'territory'], Difficulty.Basic, Topic.Environment),
  w('209', 'emissions', 'انبعاثات', 'Carbon emissions cause global warming.', ['discharge', 'release', 'fumes'], Difficulty.Intermediate, Topic.Environment),
  w('210', 'catastrophic', 'كارثي', 'Climate change has catastrophic consequences.', ['disastrous', 'devastating', 'calamitous'], Difficulty.Advanced, Topic.Environment),
  w('211', 'renewable', 'متجدد', 'Solar power is a renewable energy.', ['sustainable', 'inexhaustible'], Difficulty.Basic, Topic.Environment),
  w('212', 'ecosystem', 'نظام بيئي', 'Pollution disrupts the fragile ecosystem.', ['environment', 'biosphere'], Difficulty.Intermediate, Topic.Environment),
  w('213', 'deforestation', 'إزالة الغابات', 'Deforestation accelerates climate change.', ['logging', 'clear-cutting'], Difficulty.Intermediate, Topic.Environment),
  w('214', 'pollution', 'تلوث', 'Air pollution levels are high.', ['contamination', 'smog', 'toxins'], Difficulty.Basic, Topic.Environment),
  w('215', 'global warming', 'احتباس حراري', 'Global warming melts polar ice.', ['climate change', 'greenhouse effect'], Difficulty.Basic, Topic.Environment),
  w('216', 'ecological', 'بيئي', 'The ecological impact is severe.', ['environmental', 'biological'], Difficulty.Advanced, Topic.Environment),
  w('217', 'extinction', 'انقراض', 'Many species face extinction.', ['dying out', 'disappearance', 'annihilation'], Difficulty.Intermediate, Topic.Environment),
  w('218', 'environmentally friendly', 'صديق للبيئة', 'Use environmentally friendly products.', ['eco-friendly', 'green'], Difficulty.Basic, Topic.Environment),
  w('219', 'fossil fuels', 'وقود أحفوري', 'Burning fossil fuels creates CO2.', ['coal/oil/gas', 'non-renewable energy'], Difficulty.Intermediate, Topic.Environment),
  w('220', 'waste disposal', 'تخلص من النفايات', 'Proper waste disposal is crucial.', ['garbage removal', 'dumping'], Difficulty.Intermediate, Topic.Environment),
  w('221', 'preservation', 'حفاظ', 'Preservation of historic sites is important.', ['conservation', 'protection'], Difficulty.Intermediate, Topic.Environment),
  w('222', 'cultivate', 'يزرع / يفلح', 'They cultivate crops for food.', ['grow', 'farm', 'plant'], Difficulty.Intermediate, Topic.Environment),
  w('223', 'barren', 'قاحل', 'The land became barren due to drought.', ['infertile', 'unproductive', 'arid'], Difficulty.Advanced, Topic.Environment),
  w('224', 'irrigation', 'ري', 'Farmers use irrigation in dry seasons.', ['watering', 'hydration'], Difficulty.Advanced, Topic.Environment),
  w('225', 'landfill', 'مكب نفايات', 'Plastic waste ends up in landfills.', ['dump', 'rubbish tip'], Difficulty.Intermediate, Topic.Environment),

  // --- EDUCATION ---
  w('301', 'curriculum', 'منهج دراسي', 'The school has a strict curriculum.', ['syllabus', 'program', 'coursework'], Difficulty.Intermediate, Topic.Education),
  w('302', 'literacy', 'معرفة القراءة والكتابة', 'Literacy rates are rising.', ['reading ability', 'education'], Difficulty.Basic, Topic.Education),
  w('303', 'pedagogy', 'طرق التدريس', 'Modern pedagogy emphasizes interaction.', ['teaching methods', 'instruction'], Difficulty.Advanced, Topic.Education),
  w('304', 'illiterate', 'أمي (لا يقرأ)', 'Many adults remain illiterate.', ['uneducated', 'unable to read'], Difficulty.Intermediate, Topic.Education),
  w('305', 'discipline', 'انضباط / تخصص', 'History is an academic discipline.', ['field', 'subject', 'specialty'], Difficulty.Intermediate, Topic.Education),
  w('306', 'vocational', 'مهني', 'Vocational schools teach practical skills.', ['occupational', 'technical'], Difficulty.Intermediate, Topic.Education),
  w('307', 'tuition', 'رسوم دراسية', 'Tuition fees are very high.', ['school fees', 'instruction costs'], Difficulty.Intermediate, Topic.Education),
  w('308', 'plagiarism', 'سرقة أدبية', 'Plagiarism can lead to expulsion.', ['copying', 'theft'], Difficulty.Advanced, Topic.Education),
  w('309', 'acquisition', 'اكتساب', 'Language acquisition takes time.', ['learning', 'attainment'], Difficulty.Advanced, Topic.Education),
  w('310', 'innate', 'فطري', 'Some talent is innate.', ['inborn', 'natural', 'inherent'], Difficulty.Advanced, Topic.Education),
  w('311', 'compulsory', 'إجباري', 'Math is a compulsory subject.', ['mandatory', 'required', 'obligatory'], Difficulty.Intermediate, Topic.Education),
  w('312', 'inquisitive', 'فضولي / محب للاستطلاع', 'Children are naturally inquisitive.', ['curious', 'inquiring', 'questioning'], Difficulty.Advanced, Topic.Education),
  w('313', 'tertiary', 'تعليم جامعي', 'Tertiary education follows high school.', ['higher education', 'university level'], Difficulty.Advanced, Topic.Education),
  w('314', 'qualification', 'مؤهل', 'You need a qualification for this job.', ['credential', 'certificate', 'degree'], Difficulty.Basic, Topic.Education),
  w('315', 'theoretical', 'نظري', 'The course is too theoretical.', ['hypothetical', 'abstract', 'conceptual'], Difficulty.Intermediate, Topic.Education),
  w('316', 'cognitive', 'إدراكي', 'Puzzles improve cognitive skills.', ['mental', 'intellectual', 'cerebral'], Difficulty.Advanced, Topic.Education),
  w('317', 'assess', 'يقيم', 'Teachers assess student progress.', ['evaluate', 'judge', 'grade'], Difficulty.Intermediate, Topic.Education),
  w('318', 'extracurricular', 'لا منهجي (أنشطة)', 'Sports are extracurricular activities.', ['outside class', 'after-school'], Difficulty.Intermediate, Topic.Education),
  w('319', 'peer', 'قرين / زميل', 'Children learn from their peers.', ['fellow', 'equal', 'classmate'], Difficulty.Basic, Topic.Education),
  w('320', 'procrastinate', 'يماطل / يسوف', 'Students often procrastinate before exams.', ['delay', 'postpone', 'stall'], Difficulty.Advanced, Topic.Education),
  w('321', 'comprehensive', 'شامل', 'A comprehensive review of the subject.', ['thorough', 'complete', 'extensive'], Difficulty.Intermediate, Topic.Education),
  w('322', 'scholarship', 'منحة دراسية', 'She won a scholarship to Oxford.', ['grant', 'award', 'fellowship'], Difficulty.Basic, Topic.Education),
  w('323', 'distance learning', 'تعلم عن بعد', 'Distance learning is popular now.', ['remote study', 'online learning'], Difficulty.Basic, Topic.Education),
  w('324', 'literate', 'متعلم (يقرأ ويكتب)', 'A literate population drives growth.', ['educated', 'schooled'], Difficulty.Intermediate, Topic.Education),
  w('325', 'concentration', 'تركيز', 'Studying requires concentration.', ['focus', 'attention'], Difficulty.Basic, Topic.Education),

  // --- TECHNOLOGY ---
  w('401', 'ubiquitous', 'منتشر جدا', 'Smartphones are ubiquitous.', ['omnipresent', 'pervasive', 'widespread'], Difficulty.Advanced, Topic.Technology),
  w('402', 'obsolete', 'عفا عليه الزمن', 'DVDs are becoming obsolete.', ['outdated', 'archaic', 'outmoded'], Difficulty.Intermediate, Topic.Technology),
  w('403', 'automation', 'أتمتة', 'Automation replaces manual labor.', ['mechanization', 'robotics'], Difficulty.Advanced, Topic.Technology),
  w('404', 'innovation', 'ابتكار', 'Innovation drives the tech industry.', ['invention', 'novelty'], Difficulty.Intermediate, Topic.Technology),
  w('405', 'breakthrough', 'اختراق علمي / إنجاز', 'A breakthrough in AI research.', ['discovery', 'advance', 'leap'], Difficulty.Intermediate, Topic.Technology),
  w('406', 'cutting-edge', 'متطور جدا', 'Using cutting-edge software.', ['state-of-the-art', 'advanced'], Difficulty.Intermediate, Topic.Technology),
  w('407', 'privacy', 'خصوصية', 'Online privacy is a concern.', ['confidentiality', 'secrecy'], Difficulty.Basic, Topic.Technology),
  w('408', 'virtual', 'افتراضي', 'We held a virtual meeting.', ['digital', 'simulated'], Difficulty.Basic, Topic.Technology),
  w('409', 'appliance', 'جهاز منزلي', 'Kitchen appliances save time.', ['device', 'machine', 'gadget'], Difficulty.Basic, Topic.Technology),
  w('410', 'technophile', 'محب للتكنولوجيا', 'He is a massive technophile.', ['tech-lover', 'geek'], Difficulty.Advanced, Topic.Technology),
  w('411', 'artificial intelligence', 'ذكاء اصطناعي', 'AI transforms industries.', ['AI', 'machine learning'], Difficulty.Intermediate, Topic.Technology),
  w('412', 'cybercrime', 'جرائم إلكترونية', 'Cybercrime poses a security threat.', ['hacking', 'online crime'], Difficulty.Intermediate, Topic.Technology),
  w('413', 'device', 'جهاز', 'Mobile devices are essential.', ['gadget', 'apparatus', 'tool'], Difficulty.Basic, Topic.Technology),
  w('414', 'digitalization', 'رقمنة', 'The digitalization of records.', ['digitization', 'computerization'], Difficulty.Advanced, Topic.Technology),
  w('415', 'glitch', 'خلل فني', 'The system had a glitch.', ['bug', 'error', 'malfunction'], Difficulty.Intermediate, Topic.Technology),
  w('416', 'hardware', 'عتاد (أجهزة)', 'Computer hardware is expensive.', ['equipment', 'machinery'], Difficulty.Basic, Topic.Technology),
  w('417', 'indispensable', 'لا غنى عنه', 'Phones are indispensable today.', ['essential', 'crucial', 'vital'], Difficulty.Advanced, Topic.Technology),
  w('418', 'intuitive', 'سهل الاستخدام / بديهي', 'The app interface is intuitive.', ['user-friendly', 'instinctive'], Difficulty.Intermediate, Topic.Technology),
  w('419', 'mechanism', 'آلية', 'The locking mechanism is broken.', ['system', 'process', 'device'], Difficulty.Intermediate, Topic.Technology),
  w('420', 'prototype', 'نموذج أولي', 'They built a prototype car.', ['model', 'sample'], Difficulty.Advanced, Topic.Technology),
  w('421', 'revolutionize', 'يحدث ثورة', 'The internet revolutionized communication.', ['transform', 'change radically'], Difficulty.Advanced, Topic.Technology),
  w('422', 'sophisticated', 'متطور / معقد', 'Sophisticated software.', ['advanced', 'complex', 'refined'], Difficulty.Advanced, Topic.Technology),
  w('423', 'telecommunications', 'اتصالات', 'The telecommunications industry.', ['comms', 'transmission'], Difficulty.Advanced, Topic.Technology),
  w('424', 'user-friendly', 'سهل الاستخدام', 'Is the software user-friendly?', ['easy to use', 'accessible'], Difficulty.Basic, Topic.Technology),
  w('425', 'wireless', 'لاسلكي', 'Wireless connection is weak.', ['cordless', 'wifi'], Difficulty.Basic, Topic.Technology),

  // --- SOCIETY ---
  w('501', 'dilemma', 'معضلة', 'It was a moral dilemma.', ['predicament', 'quandary', 'problem'], Difficulty.Intermediate, Topic.Society),
  w('502', 'inevitable', 'حتمي', 'Change is inevitable.', ['unavoidable', 'inescapable', 'certain'], Difficulty.Intermediate, Topic.Society),
  w('503', 'exacerbate', 'يفاقم', 'Poverty exacerbates crime.', ['worsen', 'aggravate', 'intensify'], Difficulty.Advanced, Topic.Society),
  w('504', 'segregation', 'فصل / عزل', 'Racial segregation is wrong.', ['separation', 'isolation', 'apartheid'], Difficulty.Advanced, Topic.Society),
  w('505', 'discrimination', 'تمييز', 'Discrimination is illegal.', ['prejudice', 'bias'], Difficulty.Intermediate, Topic.Society),
  w('506', 'integration', 'دمج', 'Social integration is key.', ['assimilation', 'inclusion'], Difficulty.Intermediate, Topic.Society),
  w('507', 'demographic', 'سكاني', 'Demographic changes.', ['population', 'census'], Difficulty.Advanced, Topic.Society),
  w('508', 'urbanization', 'تحضر', 'Rapid urbanization affects cities.', ['city growth', 'urban sprawl'], Difficulty.Advanced, Topic.Society),
  w('509', 'poverty', 'فقر', 'They live in poverty.', ['destitution', 'penury'], Difficulty.Basic, Topic.Society),
  w('510', 'juvenile', 'حدث (صغير السن)', 'Juvenile crime is rising.', ['youth', 'adolescent'], Difficulty.Intermediate, Topic.Society),
  w('511', 'infrastructure', 'بنية تحتية', 'Transport infrastructure.', ['facilities', 'systems'], Difficulty.Advanced, Topic.Society),
  w('512', 'congestion', 'ازدحام', 'Traffic congestion is bad.', ['traffic jams', 'crowding'], Difficulty.Intermediate, Topic.Society),
  w('513', 'amenity', 'مرفق / وسيلة راحة', 'Local amenities include parks.', ['facility', 'service', 'convenience'], Difficulty.Advanced, Topic.Society),
  w('514', 'commute', 'يسافر للعمل', 'He commutes to London daily.', ['travel', 'journey'], Difficulty.Basic, Topic.Society),
  w('515', 'overpopulation', 'زيادة سكانية', 'Overpopulation causes shortages.', ['crowding', 'population density'], Difficulty.Intermediate, Topic.Society),
  w('516', 'slum', 'حي فقير', 'Many live in slums.', ['shanty town', 'ghetto'], Difficulty.Intermediate, Topic.Society),
  w('517', 'cosmopolitan', 'عالمي / متعدد الثقافات', 'London is a cosmopolitan city.', ['multicultural', 'international'], Difficulty.Advanced, Topic.Society),
  w('518', 'migration', 'هجرة', 'Bird migration patterns.', ['movement', 'relocation'], Difficulty.Intermediate, Topic.Society),
  w('519', 'standard of living', 'مستوى المعيشة', 'The standard of living rose.', ['quality of life', 'prosperity'], Difficulty.Intermediate, Topic.Society),
  w('520', 'socialize', 'يخالط الناس', 'He likes to socialize.', ['mix', 'mingle'], Difficulty.Basic, Topic.Society),
  w('521', 'stereotype', 'صورة نمطية', 'Cultural stereotypes can be harmful.', ['cliché', 'label', 'typecast'], Difficulty.Intermediate, Topic.Society),
  w('522', 'prejudice', 'تحيز / حكم مسبق', 'Racial prejudice.', ['bias', 'bigotry', 'discrimination'], Difficulty.Advanced, Topic.Society),
  w('523', 'welfare', 'رفاهية / رعاية اجتماعية', 'The state welfare system.', ['well-being', 'social security'], Difficulty.Intermediate, Topic.Society),
  w('524', 'household', 'أسرة / منزل', 'Average household income.', ['family', 'home'], Difficulty.Basic, Topic.Society),
  w('525', 'norm', 'عرف / معيار', 'Social norms vary.', ['standard', 'convention', 'rule'], Difficulty.Intermediate, Topic.Society),

  // --- HEALTH ---
  w('601', 'obesity', 'سمنة', 'Obesity causes heart disease.', ['overweight', 'fatness'], Difficulty.Intermediate, Topic.Health),
  w('602', 'sedentary', 'خامل', 'A sedentary lifestyle is bad.', ['inactive', 'sitting'], Difficulty.Advanced, Topic.Health),
  w('603', 'epidemic', 'وباء', 'The flu epidemic.', ['outbreak', 'plague'], Difficulty.Intermediate, Topic.Health),
  w('604', 'nutritious', 'مغذي', 'Eat nutritious food.', ['healthy', 'wholesome'], Difficulty.Basic, Topic.Health),
  w('605', 'longevity', 'طول العمر', 'Diet affects longevity.', ['lifespan', 'endurance'], Difficulty.Advanced, Topic.Health),
  w('606', 'chronic', 'مزمن', 'Chronic pain.', ['persistent', 'long-term'], Difficulty.Advanced, Topic.Health),
  w('607', 'prevalent', 'منتشر', 'The disease is prevalent.', ['widespread', 'common'], Difficulty.Intermediate, Topic.Health),
  w('608', 'hygiene', 'نظافة', 'Personal hygiene.', ['cleanliness', 'sanitation'], Difficulty.Basic, Topic.Health),
  w('609', 'addiction', 'إدمان', 'Drug addiction.', ['dependency', 'craving'], Difficulty.Intermediate, Topic.Health),
  w('610', 'diagnosis', 'تشخيص', 'Early diagnosis is key.', ['identification', 'analysis'], Difficulty.Intermediate, Topic.Health),
  w('611', 'rehabilitation', 'إعادة تأهيل', 'Rehabilitation center.', ['recovery', 'treatment'], Difficulty.Advanced, Topic.Health),
  w('612', 'contagious', 'معدي', 'The flu is contagious.', ['infectious', 'transmissible'], Difficulty.Intermediate, Topic.Health),
  w('613', 'fatigue', 'إعياء', 'Chronic fatigue.', ['tiredness', 'exhaustion'], Difficulty.Intermediate, Topic.Health),
  w('614', 'vaccination', 'تلقيح', 'Vaccination prevents disease.', ['immunization', 'shot'], Difficulty.Basic, Topic.Health),
  w('615', 'malnutrition', 'سوء تغذية', 'Malnutrition in children.', ['starvation', 'poor diet'], Difficulty.Intermediate, Topic.Health),
  w('616', 'symptom', 'عرض (مرض)', 'Fever is a symptom.', ['sign', 'indication'], Difficulty.Basic, Topic.Health),
  w('617', 'obese', 'بدين', 'He is clinically obese.', ['very fat', 'overweight'], Difficulty.Basic, Topic.Health),
  w('618', 'metabolism', 'تمثيل غذائي', 'Exercise boosts metabolism.', ['digestion', 'energy burn'], Difficulty.Advanced, Topic.Health),
  w('619', 'cardiovascular', 'قلبي وعائي', 'Cardiovascular health.', ['heart-related'], Difficulty.Advanced, Topic.Health),
  w('620', 'insomnia', 'أرق', 'Suffering from insomnia.', ['sleeplessness'], Difficulty.Advanced, Topic.Health),
  w('621', 'immune system', 'جهاز مناعي', 'Strengthen your immune system.', ['defense system'], Difficulty.Intermediate, Topic.Health),
  w('622', 'dehydration', 'جفاف', 'Drink water to avoid dehydration.', ['dryness', 'lack of water'], Difficulty.Basic, Topic.Health),
  w('623', 'therapeutic', 'علاجي', 'Massage is therapeutic.', ['healing', 'remedial', 'curative'], Difficulty.Advanced, Topic.Health),
  w('624', 'deficiency', 'نقص', 'Vitamin deficiency.', ['shortage', 'lack'], Difficulty.Intermediate, Topic.Health),
  w('625', 'vital', 'حيوي', 'Vital organs.', ['essential', 'critical', 'life-sustaining'], Difficulty.Intermediate, Topic.Health),

  // --- WORK / ECONOMY ---
  w('701', 'revenue', 'إيرادات', 'Company revenue increased.', ['income', 'earnings'], Difficulty.Intermediate, Topic.Economy),
  w('702', 'incentive', 'حافز', 'Tax incentives.', ['motivation', 'encouragement'], Difficulty.Intermediate, Topic.Economy),
  w('703', 'productivity', 'إنتاجية', 'Boost productivity.', ['efficiency', 'output'], Difficulty.Intermediate, Topic.Work),
  w('704', 'entrepreneur', 'رائد أعمال', 'A successful entrepreneur.', ['businessperson', 'founder'], Difficulty.Advanced, Topic.Economy),
  w('705', 'monopoly', 'احتكار', 'A state monopoly.', ['dominance', 'exclusive control'], Difficulty.Advanced, Topic.Economy),
  w('706', 'outsourcing', 'تعاقد خارجي', 'Outsourcing jobs.', ['subcontracting'], Difficulty.Advanced, Topic.Work),
  w('707', 'expenditure', 'نفقات', 'Government expenditure.', ['spending', 'expenses'], Difficulty.Advanced, Topic.Economy),
  w('708', 'bankruptcy', 'إفلاس', 'Facing bankruptcy.', ['insolvency', 'ruin'], Difficulty.Intermediate, Topic.Economy),
  w('709', 'collaboration', 'تعاون', 'Close collaboration.', ['cooperation', 'partnership'], Difficulty.Intermediate, Topic.Work),
  w('710', 'employee', 'موظف', 'A dedicated employee.', ['worker', 'staff'], Difficulty.Basic, Topic.Work),
  w('711', 'employer', 'رب عمل', 'The employer pays wages.', ['boss', 'manager'], Difficulty.Basic, Topic.Work),
  w('712', 'promotion', 'ترقية', 'She got a promotion.', ['advancement', 'upgrade'], Difficulty.Basic, Topic.Work),
  w('713', 'resignation', 'استقالة', 'Hand in resignation.', ['departure', 'quitting'], Difficulty.Intermediate, Topic.Work),
  w('714', 'unemployment', 'بطالة', 'High unemployment rates.', ['joblessness'], Difficulty.Basic, Topic.Economy),
  w('715', 'wage', 'أجر', 'Minimum wage.', ['salary', 'pay', 'earnings'], Difficulty.Basic, Topic.Work),
  w('716', 'salary', 'راتب', 'Annual salary.', ['pay', 'wage'], Difficulty.Basic, Topic.Work),
  w('717', 'pension', 'راتب تقاعد', 'Retirement pension.', ['allowance', 'benefit'], Difficulty.Intermediate, Topic.Economy),
  w('718', 'deficit', 'عجز (مالي)', 'Budget deficit.', ['shortfall', 'loss'], Difficulty.Advanced, Topic.Economy),
  w('719', 'inflation', 'تضخم', 'Inflation affects prices.', ['price rise'], Difficulty.Intermediate, Topic.Economy),
  w('720', 'subsidize', 'يدعم ماليا', 'The government subsidizes farming.', ['fund', 'sponsor', 'support'], Difficulty.Advanced, Topic.Economy),
  w('721', 'consumer', 'مستهلك', 'Consumer rights.', ['buyer', 'customer'], Difficulty.Basic, Topic.Economy),
  w('722', 'commerce', 'تجارة', 'International commerce.', ['trade', 'business'], Difficulty.Intermediate, Topic.Economy),
  w('723', 'merger', 'اندماج (شركات)', 'A merger between two banks.', ['union', 'amalgamation'], Difficulty.Advanced, Topic.Economy),
  w('724', 'workforce', 'قوى عاملة', 'A skilled workforce.', ['staff', 'personnel'], Difficulty.Intermediate, Topic.Work),
  w('725', 'retail', 'بيع بالتجزئة', 'Retail stores.', ['selling', 'shops'], Difficulty.Intermediate, Topic.Economy),

  // --- GOVERNMENT / LAW ---
  w('801', 'legislation', 'تشريع', 'New legislation was passed.', ['law', 'statutes'], Difficulty.Advanced, Topic.Government),
  w('802', 'policy', 'سياسة', 'Foreign policy.', ['strategy', 'plan'], Difficulty.Intermediate, Topic.Government),
  w('803', 'regulation', 'لائحة / تنظيم', 'Safety regulations.', ['rule', 'control'], Difficulty.Intermediate, Topic.Government),
  w('804', 'authority', 'سلطة', 'Local authority.', ['power', 'control'], Difficulty.Basic, Topic.Government),
  w('805', 'bureaucracy', 'بيروقراطية', 'Excessive bureaucracy.', ['red tape', 'officialdom'], Difficulty.Advanced, Topic.Government),
  w('806', 'democracy', 'ديمقراطية', 'Fight for democracy.', ['self-government'], Difficulty.Basic, Topic.Government),
  w('807', 'republic', 'جمهورية', 'The French Republic.', ['state', 'nation'], Difficulty.Basic, Topic.Government),
  w('808', 'sanction', 'عقوبة / جزاء', 'Economic sanctions.', ['penalty', 'punishment'], Difficulty.Advanced, Topic.Government),
  w('809', 'amendment', 'تعديل (قانوني)', 'Constitutional amendment.', ['change', 'modification'], Difficulty.Advanced, Topic.Government),
  w('810', 'constitution', 'دستور', 'Written constitution.', ['charter', 'code'], Difficulty.Intermediate, Topic.Government),
  w('811', 'parliament', 'برلمان', 'Member of parliament.', ['congress', 'legislature'], Difficulty.Intermediate, Topic.Government),
  w('812', 'campaign', 'حملة', 'Election campaign.', ['drive', 'movement'], Difficulty.Intermediate, Topic.Government),
  w('813', 'candidate', 'مرشح', 'Presidential candidate.', ['contender', 'nominee'], Difficulty.Intermediate, Topic.Government),
  w('814', 'coalition', 'تحالف', 'A coalition government.', ['alliance', 'union'], Difficulty.Advanced, Topic.Government),
  w('815', 'corrupt', 'فاسد', 'Corrupt officials.', ['dishonest', 'unethical'], Difficulty.Intermediate, Topic.Government),
  w('816', 'implement', 'ينفذ', 'Implement a policy.', ['execute', 'apply'], Difficulty.Intermediate, Topic.Government),
  w('817', 'prohibit', 'يمنع', 'Smoking is prohibited.', ['ban', 'forbid'], Difficulty.Intermediate, Topic.Government),
  w('818', 'violation', 'انتهاك', 'Human rights violation.', ['breach', 'infringement'], Difficulty.Advanced, Topic.Government),
  w('819', 'sentence', 'حكم (قضائي)', 'He received a life sentence.', ['judgment', 'punishment'], Difficulty.Basic, Topic.Government),
  w('820', 'defendant', 'مدعى عليه', 'The defendant stood up.', ['accused'], Difficulty.Advanced, Topic.Government),
  w('821', 'prosecutor', 'مدعي عام', 'The public prosecutor.', ['lawyer'], Difficulty.Advanced, Topic.Government),
  w('822', 'verdict', 'حكم المحلفين', 'The jury reached a verdict.', ['decision', 'judgment'], Difficulty.Advanced, Topic.Government),
  w('823', 'deterrent', 'رادع', 'Prison is a deterrent.', ['discouragement', 'disincentive'], Difficulty.Advanced, Topic.Government),
  w('824', 'offender', 'مذنب / جاني', 'Young offenders.', ['criminal', 'culprit'], Difficulty.Intermediate, Topic.Government),
  w('825', 'rehabilitate', 'يصلح / يؤهل', 'Rehabilitate prisoners.', ['reform', 'restore'], Difficulty.Advanced, Topic.Government),

  // --- CULTURE & MEDIA ---
  w('901', 'heritage', 'تراث', 'Cultural heritage.', ['legacy', 'tradition'], Difficulty.Intermediate, Topic.Culture),
  w('902', 'contemporary', 'معاصر', 'Contemporary art.', ['modern', 'current'], Difficulty.Intermediate, Topic.Culture),
  w('903', 'aesthetic', 'جمالي', 'Aesthetic appeal.', ['artistic', 'visual'], Difficulty.Advanced, Topic.Culture),
  w('904', 'censorship', 'رقابة', 'Media censorship.', ['restriction', 'control'], Difficulty.Advanced, Topic.Culture),
  w('905', 'bias', 'تحيز', 'Political bias.', ['prejudice', 'leaning'], Difficulty.Intermediate, Topic.Culture),
  w('906', 'objective', 'موضوعي', 'Objective reporting.', ['unbiased', 'impartial'], Difficulty.Intermediate, Topic.Culture),
  w('907', 'subjective', 'شخصي / غير موضوعي', 'Taste is subjective.', ['personal', 'individual'], Difficulty.Intermediate, Topic.Culture),
  w('908', 'journalism', 'صحافة', 'Investigative journalism.', ['reporting', 'news'], Difficulty.Basic, Topic.Culture),
  w('909', 'broadcast', 'بث', 'Live broadcast.', ['transmission', 'airing'], Difficulty.Basic, Topic.Culture),
  w('910', 'publicity', 'دعاية / شهرة', 'Negative publicity.', ['attention', 'hype'], Difficulty.Intermediate, Topic.Culture),
  w('911', 'museum', 'متحف', 'Art museum.', ['gallery', 'exhibition'], Difficulty.Basic, Topic.Culture),
  w('912', 'artifact', 'قطعة أثرية', 'Ancient artifacts.', ['relic', 'item'], Difficulty.Advanced, Topic.Culture),
  w('913', 'tradition', 'تقليد', 'Family tradition.', ['custom', 'practice'], Difficulty.Basic, Topic.Culture),
  w('914', 'indigenous', 'أصلي (سكان)', 'Indigenous people.', ['native', 'original'], Difficulty.Advanced, Topic.Culture),
  w('915', 'globalization', 'عولمة', 'Impact of globalization.', ['international integration'], Difficulty.Advanced, Topic.Economy),
  w('916', 'dialect', 'لهجة', 'Local dialect.', ['accent', 'language'], Difficulty.Intermediate, Topic.Culture),
  w('917', 'etiquette', 'آداب السلوك', 'Business etiquette.', ['manners', 'protocol'], Difficulty.Advanced, Topic.Culture),
  w('918', 'monument', 'نصب تذكاري', 'Historic monument.', ['statue', 'shrine'], Difficulty.Intermediate, Topic.Culture),
  w('919', 'ritual', 'طقس (ديني)', 'Daily ritual.', ['ceremony', 'routine'], Difficulty.Intermediate, Topic.Culture),
  w('920', 'cuisine', 'مطبخ (طعام)', 'Italian cuisine.', ['food', 'cooking'], Difficulty.Intermediate, Topic.Culture),

  // --- GENERAL ABSTRACT (Useful for Task 2) ---
  w('1001', 'advantage', 'ميزة', 'A key advantage.', ['benefit', 'asset'], Difficulty.Basic, Topic.General),
  w('1002', 'disadvantage', 'عيب', 'A major disadvantage.', ['drawback', 'downside'], Difficulty.Basic, Topic.General),
  w('1003', 'consequence', 'عاقبة', 'Serious consequences.', ['result', 'outcome'], Difficulty.Intermediate, Topic.General),
  w('1004', 'subsequent', 'لاحق', 'Subsequent events.', ['following', 'later'], Difficulty.Intermediate, Topic.General),
  w('1005', 'significant', 'هام', 'Significant change.', ['important', 'meaningful'], Difficulty.Basic, Topic.General),
  w('1006', 'irrelevant', 'غير صلة', 'Irrelevant details.', ['unrelated', 'immaterial'], Difficulty.Intermediate, Topic.General),
  w('1007', 'appropriate', 'مناسب', 'Appropriate behavior.', ['suitable', 'fitting'], Difficulty.Basic, Topic.General),
  w('1008', 'aspect', 'جانب', 'Every aspect of life.', ['facet', 'part'], Difficulty.Intermediate, Topic.General),
  w('1009', 'category', 'فئة', 'Product category.', ['class', 'group'], Difficulty.Basic, Topic.General),
  w('1010', 'concept', 'مفهوم', 'Abstract concept.', ['idea', 'notion'], Difficulty.Intermediate, Topic.General),
  w('1011', 'distinct', 'متميز / مختلف', 'Distinct advantages.', ['clear', 'different'], Difficulty.Intermediate, Topic.General),
  w('1012', 'establish', 'يؤسس', 'Establish a rule.', ['set up', 'found'], Difficulty.Basic, Topic.General),
  w('1013', 'impact', 'تأثير', 'High impact.', ['effect', 'influence'], Difficulty.Basic, Topic.General),
  w('1014', 'indicate', 'يشير', 'Studies indicate that...', ['show', 'suggest'], Difficulty.Basic, Topic.General),
  w('1015', 'method', 'طريقة', 'New method.', ['way', 'approach'], Difficulty.Basic, Topic.General),
  w('1016', 'perspective', 'منظور', 'Different perspective.', ['viewpoint', 'angle'], Difficulty.Intermediate, Topic.General),
  w('1017', 'potential', 'محتمل / كامن', 'Potential risk.', ['possible', 'likely'], Difficulty.Basic, Topic.General),
  w('1018', 'principle', 'مبدأ', 'Basic principle.', ['rule', 'doctrine'], Difficulty.Intermediate, Topic.General),
  w('1019', 'relevant', 'ذو صلة', 'Relevant information.', ['pertinent', 'applicable'], Difficulty.Intermediate, Topic.General),
  w('1020', 'specific', 'محدد', 'Specific instructions.', ['particular', 'precise'], Difficulty.Basic, Topic.General),
  w('1021', 'structure', 'هيكل', 'Social structure.', ['organization', 'framework'], Difficulty.Basic, Topic.General),
  w('1022', 'theory', 'نظرية', 'Scientific theory.', ['hypothesis', 'thesis'], Difficulty.Basic, Topic.General),
  w('1023', 'vary', 'يختلف', 'Results vary.', ['differ', 'change'], Difficulty.Basic, Topic.General),
  w('1024', 'accumulate', 'يتراكم', 'Evidence accumulated.', ['gather', 'collect'], Difficulty.Intermediate, Topic.General),
  w('1025', 'acquire', 'يكتسب', 'Acquire skills.', ['gain', 'obtain'], Difficulty.Intermediate, Topic.General),
  w('1026', 'adapt', 'يتكيف', 'Adapt to change.', ['adjust', 'modify'], Difficulty.Basic, Topic.General),
  w('1027', 'adequate', 'كاف', 'Adequate resources.', ['sufficient', 'enough'], Difficulty.Intermediate, Topic.General),
  w('1028', 'advocate', 'يؤيد', 'Advocate for change.', ['support', 'promote'], Difficulty.Intermediate, Topic.General),
  w('1029', 'allocate', 'يخصص', 'Allocate funds.', ['assign', 'distribute'], Difficulty.Advanced, Topic.General),
  w('1030', 'alter', 'يغير', 'Alter plans.', ['change', 'modify'], Difficulty.Basic, Topic.General),
  w('1031', 'alternative', 'بديل', 'Alternative energy.', ['substitute', 'option'], Difficulty.Basic, Topic.General),
  w('1032', 'ambiguous', 'غامض', 'Ambiguous ending.', ['unclear', 'vague'], Difficulty.Advanced, Topic.General),
  w('1033', 'analogy', 'تشبيه / قياس', 'Draw an analogy.', ['comparison', 'parallel'], Difficulty.Advanced, Topic.General),
  w('1034', 'anticipate', 'يتوقع', 'Anticipate problems.', ['expect', 'foresee'], Difficulty.Intermediate, Topic.General),
  w('1035', 'apparent', 'ظاهر / واضح', 'It became apparent.', ['obvious', 'clear'], Difficulty.Intermediate, Topic.General),
  w('1036', 'arbitrary', 'اعتباطي / عشوائي', 'Arbitrary decision.', ['random', 'chance'], Difficulty.Advanced, Topic.General),
  w('1037', 'attribute', 'ينسب إلى', 'Attribute success to hard work.', ['ascribe', 'credit'], Difficulty.Advanced, Topic.General),
  w('1038', 'beneficial', 'مفيد', 'Beneficial effect.', ['helpful', 'advantageous'], Difficulty.Basic, Topic.General),
  w('1039', 'capacity', 'سعة / قدرة', 'Storage capacity.', ['volume', 'ability'], Difficulty.Intermediate, Topic.General),
  w('1040', 'clarify', 'يوضح', 'Clarify the point.', ['explain', 'clear up'], Difficulty.Basic, Topic.General),
  w('1041', 'coherent', 'متماسك', 'Coherent argument.', ['logical', 'consistent'], Difficulty.Advanced, Topic.General),
  w('1042', 'coincide', 'يتزامن', 'Dates coincide.', ['happen together', 'correspond'], Difficulty.Intermediate, Topic.General),
  w('1043', 'collapse', 'ينهي', 'The roof collapsed.', ['fall down', 'cave in'], Difficulty.Basic, Topic.General),
  w('1044', 'commodity', 'سلعة', 'Valuable commodity.', ['product', 'goods'], Difficulty.Advanced, Topic.General),
  w('1045', 'compensate', 'يعوض', 'Compensate for loss.', ['repay', 'make up for'], Difficulty.Intermediate, Topic.General),
  w('1046', 'complement', 'يكمل', 'Wine complements food.', ['enhance', 'complete'], Difficulty.Advanced, Topic.General),
  w('1047', 'complex', 'معقد', 'Complex problem.', ['complicated', 'intricate'], Difficulty.Basic, Topic.General),
  w('1048', 'component', 'مكون', 'Key component.', ['part', 'element'], Difficulty.Intermediate, Topic.General),
  w('1049', 'comprise', 'يتألف من', 'The team comprises 5 people.', ['consist of', 'contain'], Difficulty.Advanced, Topic.General),
  w('1050', 'conceive', 'يتصور', 'Conceive an idea.', ['imagine', 'visualize'], Difficulty.Advanced, Topic.General),
  w('1051', 'conduct', 'يجري (تجربة)', 'Conduct a survey.', ['perform', 'carry out'], Difficulty.Intermediate, Topic.General),
  w('1052', 'confine', 'يحصر / يقيد', 'Confined to bed.', ['restrict', 'limit'], Difficulty.Intermediate, Topic.General),
  w('1053', 'consensus', 'إجماع', 'Reach a consensus.', ['agreement', 'unity'], Difficulty.Advanced, Topic.General),
  w('1054', 'consent', 'موافقة', 'Written consent.', ['permission', 'agreement'], Difficulty.Intermediate, Topic.General),
  w('1055', 'contradict', 'يناقض', 'Evidence contradicts claims.', ['oppose', 'deny'], Difficulty.Intermediate, Topic.General),
  w('1056', 'controversy', 'جدل', 'Caused controversy.', ['dispute', 'debate'], Difficulty.Intermediate, Topic.General),
  w('1057', 'conventional', 'تقليدي', 'Conventional medicine.', ['traditional', 'standard'], Difficulty.Intermediate, Topic.General),
  w('1058', 'convey', 'ينقل (فكرة)', 'Convey a message.', ['communicate', 'express'], Difficulty.Intermediate, Topic.General),
  w('1059', 'criterion', 'معيار', 'Selection criterion.', ['standard', 'measure'], Difficulty.Advanced, Topic.General),
  w('1060', 'crucial', 'حاسم', 'Crucial moment.', ['vital', 'critical'], Difficulty.Intermediate, Topic.General),
  w('1061', 'deduce', 'يستنتج', 'Deduce the answer.', ['infer', 'conclude'], Difficulty.Advanced, Topic.General),
  w('1062', 'denote', 'يدل على', 'X denotes the value.', ['indicate', 'signify'], Difficulty.Advanced, Topic.General),
  w('1063', 'derive', 'يشتق', 'Derive pleasure from.', ['get', 'obtain'], Difficulty.Advanced, Topic.General),
  w('1064', 'detect', 'يكتشف', 'Detect a signal.', ['discover', 'notice'], Difficulty.Intermediate, Topic.General),
  w('1065', 'deviate', 'ينحرف', 'Deviate from the plan.', ['diverge', 'stray'], Difficulty.Advanced, Topic.General),
  w('1066', 'differentiate', 'يميز', 'Differentiate between twins.', ['distinguish', 'discriminate'], Difficulty.Intermediate, Topic.General),
  w('1067', 'dimension', 'بعد', 'New dimension.', ['aspect', 'feature'], Difficulty.Intermediate, Topic.General),
  w('1068', 'diminish', 'يقلل', 'Diminish returns.', ['decrease', 'lessen'], Difficulty.Intermediate, Topic.General),
  w('1069', 'discrepancy', 'تضارب / اختلاف', 'Discrepancy in figures.', ['inconsistency', 'difference'], Difficulty.Advanced, Topic.General),
  w('1070', 'discrete', 'منفصل', 'Discrete steps.', ['separate', 'distinct'], Difficulty.Advanced, Topic.General),
  w('1071', 'distort', 'يشوه', 'Distort the truth.', ['twist', 'misrepresent'], Difficulty.Advanced, Topic.General),
  w('1072', 'diverse', 'متنوع', 'Diverse group.', ['varied', 'different'], Difficulty.Intermediate, Topic.General),
  w('1073', 'dominate', 'يسيطر', 'Dominate the market.', ['control', 'command'], Difficulty.Basic, Topic.General),
  w('1074', 'dynamic', 'ديناميكي', 'Dynamic environment.', ['active', 'changing'], Difficulty.Intermediate, Topic.General),
  w('1075', 'eliminate', 'يزيل', 'Eliminate waste.', ['remove', 'get rid of'], Difficulty.Intermediate, Topic.General),
  w('1076', 'emerge', 'يظهر', 'Problems emerged.', ['appear', 'arise'], Difficulty.Basic, Topic.General),
  w('1077', 'emphasis', 'تأكيد', 'Emphasis on quality.', ['stress', 'importance'], Difficulty.Intermediate, Topic.General),
  w('1078', 'empirical', 'تجريدي', 'Empirical evidence.', ['experimental', 'observed'], Difficulty.Advanced, Topic.General),
  w('1079', 'encounter', 'يواجه', 'Encounter difficulties.', ['face', 'meet'], Difficulty.Intermediate, Topic.General),
  w('1080', 'enormous', 'ضخم', 'Enormous amount.', ['huge', 'vast'], Difficulty.Basic, Topic.General),
  w('1081', 'ensure', 'يضمن', 'Ensure safety.', ['guarantee', 'make sure'], Difficulty.Basic, Topic.General),
  w('1082', 'entity', 'كيان', 'Legal entity.', ['organization', 'body'], Difficulty.Advanced, Topic.General),
  w('1083', 'equivalent', 'مكافئ', 'Equivalent value.', ['equal', 'same'], Difficulty.Intermediate, Topic.General),
  w('1084', 'erode', 'يتآكل', 'Erode confidence.', ['wear away', 'undermine'], Difficulty.Advanced, Topic.General),
  w('1085', 'ethical', 'أخلاقي', 'Ethical dilemma.', ['moral', 'principled'], Difficulty.Intermediate, Topic.General),
  w('1086', 'evaluate', 'يقيم', 'Evaluate the results.', ['assess', 'judge'], Difficulty.Intermediate, Topic.General),
  w('1087', 'eventual', 'نهائي', 'Eventual success.', ['final', 'ultimate'], Difficulty.Intermediate, Topic.General),
  w('1088', 'evident', 'واضح', 'It was evident.', ['obvious', 'clear'], Difficulty.Basic, Topic.General),
  w('1089', 'evolve', 'يتطور', 'Evolve over time.', ['develop', 'progress'], Difficulty.Intermediate, Topic.General),
  w('1090', 'exceed', 'يتجاوز', 'Exceed expectations.', ['surpass', 'go beyond'], Difficulty.Intermediate, Topic.General),
  w('1091', 'exclude', 'يستبعد', 'Exclude possibility.', ['leave out', 'omit'], Difficulty.Basic, Topic.General),
  w('1092', 'exhibit', 'يعرض', 'Exhibit signs.', ['show', 'display'], Difficulty.Intermediate, Topic.General),
  w('1093', 'explicit', 'صريح', 'Explicit instructions.', ['clear', 'direct'], Difficulty.Intermediate, Topic.General),
  w('1094', 'exploit', 'يستغل', 'Exploit resources.', ['use', 'utilize'], Difficulty.Intermediate, Topic.General),
  w('1095', 'facilitate', 'يسهل', 'Facilitate learning.', ['make easy', 'assist'], Difficulty.Advanced, Topic.General),
  w('1096', 'finite', 'محدود', 'Finite resources.', ['limited', 'restricted'], Difficulty.Advanced, Topic.General),
  w('1097', 'flexible', 'مرن', 'Flexible schedule.', ['adaptable', 'pliable'], Difficulty.Basic, Topic.General),
  w('1098', 'formulate', 'يصيغ', 'Formulate a plan.', ['devise', 'create'], Difficulty.Advanced, Topic.General),
  w('1099', 'generate', 'يولد', 'Generate power.', ['produce', 'create'], Difficulty.Intermediate, Topic.General),
  w('1100', 'guarantee', 'يضمن', 'Guarantee results.', ['ensure', 'promise'], Difficulty.Basic, Topic.General),

];